version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/public/uploads:rw
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    user: "1001:1001"  # Run as nextjs user

volumes:
  uploads:
    driver: local 